#!/bin/bash

KEYFILE="keystore"
KEY_ALIAS="andrudio_demo"
STORE_PASSWORD="$1"
KEY_PASSWORD="$1"
cd `dirname $0` && cd ..

../gradlew assembleRelease -Pandroid.injected.signing.store.file=$KEYFILE \
  -Pandroid.injected.signing.store.password=$STORE_PASSWORD \
  -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
  -Pandroid.injected.signing.key.password=$KEY_PASSWORD


